### ISSUE TITLE
Expand xdt transforms to support all config files, not just web.config

### ISSUE THREAD

**Issue by seankearney** [sayedihashimi/package-web#51]
Ideally PackageWeb would produce a web deploy package that can have transforms applied to all config files, not just the web .config file.

**Comment by sayedihashimi** [comment]
I think I have something working here. I just pushed version `1.1.14-beta` to nuget.org for testing. Can you try it out and let me know what you find out?

**Comment by seankearney** [comment]
These changes broke the typical case where there is just a web.config transform. Exception is as follows:

```
9/3/2013 8:38:09 AM: An Error Occurred:
Write-Error : An error has occurred around line [], message = [System.Management.Automation.ItemNotFoundException: Cannot find path 'C:\Users\user\AppData\Local\Temp\Site.Web_zip\Content\website\_Deploy_\transforms\' because it does not exist.
   at System.Management.Automation.LocationGlobber.ExpandMshGlobPath(String path, Boolean allowNonexistingPaths, PSDriveInfo drive, ContainerCmdletProvider provider, CmdletProviderContext context)
   at System.Management.Automation.LocationGlobber.ResolveDriveQualifiedPath(String path, CmdletProviderContext context, Boolean allowNonexistingPaths, CmdletProvider& providerInstance)
   at System.Management.Automation.LocationGlobber.GetGlobbedMonadPathsFromMonadPath(String path, Boolean allowNonexistingPaths, CmdletProviderContext context, CmdletProvider& providerInstance)
   at System.Management.Automation.SessionStateInternal.SetLocation(String path, CmdletProviderContext context)
   at System.Management.Automation.PathIntrinsics.SetLocation(String path, CmdletProviderContext context)
   at Microsoft.PowerShell.Commands.SetLocationCommand.ProcessRecord()]
At C:\Users\user\Desktop\New folder\_2013.09.03-08.37.21\Publish-Interactive.ps1:1021 char:16
    +     Write-Error <<<<  $errorString
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Microsoft.PowerShell.Commands.WriteErrorCommand
```

It looks like around line 203 of Publish-Interactive.ps1 you need to `Test-Path` before you try to `Set-Location`.

**Comment by seankearney** [comment]
Looks good! Thanks Sayed!!!
